name: anime_character_tierlist
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  app_links: ^6.4.0
  auto_route: ^10.0.1
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  path_provider: ^2.1.5
  retry: ^3.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: any

flutter:
  uses-material-design: true
