name: anime_character_tierlist
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  app_links: ^6.4.0
  collection: ^1.19.1
  crypto: ^3.0.6
  dart_mappable: ^4.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  jikan_api: ^2.2.1
  path_provider: ^2.1.1
  rate_limiter: ^1.0.0
  retry: ^3.1.2
  shared_preferences: ^2.5.2
  token_bucket: ^0.9.7-pre
  url_launcher: ^6.3.1
  sqlite3_flutter_libs: ^0.5.32
  path: ^1.8.3
  drift_flutter: ^0.2.4
  drift: ^2.26.1
  drift_dev: ^2.26.1
  sqlite3: ^2.7.5
  drag_and_drop_lists: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true
